streamx:
  blueprints:
    indexable-resources-producer:
      index-fragments: false

      search-feed-extractor:
        xpath:
          fields:
            no-index:
              no-index: true
              facet: false
              element-selector: "//*[local-name()='meta'][@name='robots']"
              key: robots
              value: noindex

            eds:
              facet: true
              element-selector: "//*[local-name()='meta'][starts-with(@property, 'facets:')]"
              key-selector: "./@property"
              value-selector: "./@content"
              key-processors:
                - name: trim
                - name: lowercase
                - name: removeStart
                  config: "facets:"
              value-processors:
                - name: trim

            field-description:
              facet: false
              element-selector: "//*[local-name()='meta'][@name='description']"
              key: description
              value-selector: "./@content"

            date:
              facet: false
              element-selector: "//*[local-name()='meta'][@name='date']"
              key: date
              value-selector: "./@content"

            publication-date:
              facet: false
              element-selector: "//*[local-name()='meta'][@name='publication_date']"
              key: publication_date
              value-selector: "./@content"

            modification-date:
              facet: false
              element-selector: "//*[local-name()='meta'][@name='modification_date']"
              key: modification_date
              value-selector: "./@content"

            author:
              facet: false
              element-selector: "//*[local-name()='meta'][@name='author']"
              key: author
              value-selector: "./@content"

            adapt-to-year:
              facet: false
              element-selector: "//*[local-name()='link'][@rel='canonical']"
              key: year
              value-selector: "substring-before(substring-after(./@href, 'https://adapt.to/'), '/')"


