---
global:
  services:
    edge:
      opensearch-sink:
        replicas: 1
        stateful: true

clusters:
  eu-central-waw-edge:
    enabled: true
    overlay: {}
  eu-west-par-processing:
    enabled: true
    overlay: {}
