---
global:
  services:
    ingestion:
      rest-ingestion:
        replicas: 1
    processing:
      indexable-resources-sql-transformer:
        stateful: true
clusters:
  eu-central-waw-edge:
    enabled: true
    overlay: {}
  eu-west-par-processing:
    enabled: true
    overlay: {}
